config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/show'
  root to: "pages#home"

  resources :users do
    resources :reviews
  end

  resources :cars do
    resources :rentals, only: [:new, :create]
  end

  get "my_bookings", to: "rentals#booked_cars", as: "my_bookings"
  get "my_bookings/:id", to: "rentals#show_booked_car", as: "show_booked_rental"
  get "my_bookings/:id/receive", to: "rentals#rental_receive", as: "receive_rental"
  get "my_bookings/:id/return", to: "rentals#rental_return", as: "return_rental"
  get "my_rented_cars/:id/deliver", to: "rentals#owner_rental_deliver", as: "owner_deliver_rental"
  get "my_rented_cars/:id/receive", to: "rentals#owner_rental_receive", as: "owner_receive_rental"
  get "my_rented_cars", to: "rentals#my_rented_cars", as: "my_rented_cars"
  get "my_rented_cars/:id", to: "rentals#show_owner_rental", as: "show_owner_rental"
  patch "rental/:id/owner_acceptance", to: "rentals#update_owner_acceptance", as: "accept_rental"

  resources :rentals do

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-3" style="height: 400px; border-top: solid 2px black;">
<div class="container" style="margin-top:100px;">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
    <div class="d-flex justify-content-around">
      <div>
          <h6>Home</h6>
          <h6>Help</h6>
          <h6>Work with us</h6>
      </div>
      <div>
          <h6>About</h6>
          <h6>Terms</h6>
          <h6>Guideline</h6>
      </div>
    </div>
    <hr>
      <div class="d-flex justify-content-center mt-4">
        <div style="width: 100px;"class="d-flex justify-content-around">
          <i class="fa-brands fa-twitter"></i>
          <i class="fa-brands fa-facebook"></i>
          <i class="fa-brands fa-instagram"></i>
        </div>

      </div>
      <div class="d-flex justify-content-center mt-4">
        <h5>Ventri.com</h5>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_home_container.html.erb
<header style="background-image: URL('https://wallpapercave.com/wp/wp5055279.jpg'); height: 75vh;">
  <%# <form class="example" action="action_page.php">
    <input type="text" placeholder="Search your car.." name="search" style="width: 300px">
    <button type="submit"></button>
  </form> %>

<div style= "position: relative; height: 75vh">

<div class="d-flex align-items-center;" style="position: relative; left: 35vw; width: 30vw;">
  <div style="background-color: none; position: relative; top: 6vh;">
    <h1 style="color:white;">Custom car rentals</h1>
    <h2 style="color:white;">Are you ready for Adventure?</h2>
    <h3 style="color:white;">Let's begin...</h3>
    <div class="d-flex mt-4">
      <%= link_to "See Cars!", cars_path, class:"btn btn-outline-success", style:"width:200px"%>
    </div>
    </div>
  </div>
</div>
</div>
</header>

app/views/shared/_logged_in_body.html.erb
<div class="d-flex" style="">
  <div>
    <div class="d-flex">
      <div class="" style="margin-top: 50px; margin-left: 80px; height: 200px; ">
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, height: 150, width: 150, class:"mt-4", style:"border-radius: 50%;" %>
        <% else %>
          <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png", height: 150, width: 150, class:"mt-4", style:"border-radius:50%"%>
        <% end %>
        <h5 class="mt-3 ms-2">Hello <%= current_user.first_name %></h5>
      </div>

      <div class="" style="margin-top: 70px; border-radius: 8px; margin-left: 50px; height: 150px;; width: 600px; background: white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
        <div class="mt-2 ms-3">
          <h4 class="" style="font-weight:bold"><i class="fa-solid fa-car-side"></i> Rent out your car!</h4>
          <%= link_to "Publish your car", new_car_path, style:"width:500px", class:"mt-4 ms-4 btn btn-dark" %>
        </div>
      </div>
    </div>

    <div class="" style="margin-top: 50px; padding-bottom:30px; border-radius: 8px; margin-left: 80px; height:; width: 800px; background: white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
      <div class="container" style="margin-top: 20px;">
          <h3 style="font-weight:bold; padding-top: 20px;" class=""><i style="font-size: 20px; color:black" class="fa-solid fa-bell"></i> Pending actions </h3>
          <hr>
          <% if current_user.cars != []  %>
            <% cars = current_user.cars %>
            <% cars.each do |car| %>
              <% rentals = Rental.where(car_id: car.id) %>
              <% rentals.each do |rental|%>
                <% if rental.owner_acceptance == false %>
                  <div class="mt-3 d-flex justify-content-between">
                    <div class="">
                      <% user = User.find(rental.user_id) %>
                      <% if user.avatar.attached? %>
                        <%= cl_image_tag user.avatar.key, height: 40, width: 40, crop: :fill %>
                      <% else %>
                        <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png", height: 40, width: 40, crop: :fill,  class:"avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                      <% end %>
                      <%= "#{user.first_name} has sent you a request for model #{car.model}" %>
                    </div>
                    <%= link_to "View", my_rented_cars_path(rental), class:"btn btn-light", style:"padding-bottom:30px; height:30px"%>
                  </div>
                <% end %>
                <% if rental.owner_acceptance == true %>

                <% end %>
              <% end %>
            <% end %>
          <% end %>


          <% if  %>

          <% end %>
      </div>
    </div>

    <div class="mt-4" style="border-radius: 8px; padding-bottom:30px; margin-left: 80px; width: 800px; background: white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
      <div class="container">
        <h4 style="font-weight:bold; padding-top: 20px;"><i class="fa-solid fa-phone"></i> Your bookings</h4>
        <hr>
        <%# if user has bookings at the moment %>
        <% if current_user.rentals != [] %>
          <% rentals = Rental.where(user_id: current_user.id) %>
          <% rentals.each do |rental| %>
            <% car = Car.find(rental.car_id) %>

           <div class="d-flex justify-content-between">
              <div class="d-flex">
                <% photos = car.photos %>
                <%= cl_image_tag photos[0].key, width: 100, height: 100, crop: :fill,  class:"mt-2 mb-2"%>
                <div class="ps-3">
                  <p>Model: <%= car.model %></p>
                  <% if rental.owner_acceptance == true %>
                    <div class="d-flex">
                    <p>Acceptance:<p>
                    <i class="ms-3 fa-solid fa-check"></i>
                    </div>
                  <% else rental.owner_acceptance == false %>
                    <div class="d-flex">
                    <p>Acceptance:<p>
                    <i class="ms-3 fa-solid fa-x"></i>
                    </div>
                  <% end %>
                  <p>Pickup location: <%= car.address%></p>
                  </div>
              </div>


              <%= link_to "View", show_booked_rental_path(rental), class:"btn btn-light", style:"padding-bottom:30px; height:30px"%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

     <div class="mt-4" style=" padding-bottom: 30px;border-radius: 8px; margin-left: 80px; width: 800px; background: white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
       <div class="container">
        <h4 style="font-weight:bold; padding-top:20px"><i class="fa-solid fa-car"></i> My posted cars</h4>
        <hr>
          <% if current_user.cars != [] %>
            <% lenting_car = current_user.cars %>
          <%# get the car detail %>
            <% lenting_car.each do |car| %>
            <div class="d-flex justify-content-between">
              <div class="d-flex">
                 <% photos = car.photos %>
                <%= cl_image_tag photos[0].key, width: 100, height: 100, crop: :fill%>
                <div class="ps-3">
                  <p>Brand: <%= car.brand %></p>
                  <p>Category: <%= car.category%></p>
                  <p>Model: <%= car.model %></p>
                  <hr>
                </div>
              </div>
              <%= link_to "Show", car_path(car), class:"btn btn-light", style:"height: 40px;"%>
            </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>

  <div class="" style="padding-bottom: 30px;border-radius: 8px; margin-top: 50px; margin-left: 40px; margin-right:20px; width: 440px; background: white; box-shadow: 0 0 15px rgba(0,0,0,0.2); ">
    <h3 style="font-weight:bold"><i class="ms-3 mt-2 fa-solid fa-fire"></i> New cars</h3>
    <% @cars.each do |car|%>
    <div class="card mb-3" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 350px; border-radius:10px; margin: 0 auto">
      <% images = car.photos %>
      <%= cl_image_tag images[0].key, height:200, width: 348, crop: :fill, style:"border-radius:10px;"%>
      <div style="height: 100px"class="card-body d-flex justify-content-between">
        <div class="">
          <p class="card-text">Brand: <%= car.brand %></p>
          <p class="card-text">Model: <%= car.model  %></p>
        </div>
        <%= link_to "Show", car_path(car), class:"btn btn-light", style:"height: 40px;"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h1 style="font-weight:bold; color:white;">Ventri</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_with url: cars_path, method: :get, class: "d-flex ms-4" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a car",
        style:"border-radius: 25px 0px 0px 25px; width: 20vw;"
      %>
      <%= text_field_tag :address,
        params[:address],
        class: "form-control",
        placeholder: "Find a car by address",
        style: "border-right: none; margin-left:1px; width: 20vw;"
      %>
      <%= submit_tag "Search", class: "btn btn-success", style: "border-radius: 0 25px 25px 0; border-left:none; position: relative; right: 1px;" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link me-2" %>
          </li>
            <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, height: 40, width: 40, crop: :fill,  class:"avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png", height: 40, width: 40, crop: :fill,  class:"avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My page", users_show_path(current_user), class: "dropdown-item" %>
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "My rented cars", my_rented_cars_path, class: "dropdown-item" %>
              <%= link_to "Edit user information", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <%= link_to "/", class: "navbar-brand ms-2" do %>
            <h1 style="font-weight:bold; color:white;">Ventri</h1>
          <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="ms-3 nav-item active">
                  <%= link_to "Sign up", new_user_registration_path, class:"btn", style:"color:white; width:100px"  %>
                </li>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class:"btn", style:"color:white; width:100px"   %>
                </li>
                <div class="dropdown">
                <button class="ms-1 btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Support
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item" href="#">About</a></li>
                  <li><a class="dropdown-item" href="#">FAQ</a></li>
                  <li><a class="dropdown-item" href="#">Contact</a></li>
                </ul>
              </div>
            </ul>
              <%# <form class="ms-5 form-inline d-flex">
                <input class="form-control mr-sm-2" style="width: 300px" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form> %>

              <%= form_with url: cars_path, method: :get, class: "d-flex ms-4" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Find a car",
                style:"border-radius: 25px 0px 0px 25px; width: 20vw;"
              %>
              <%= text_field_tag :address,
                params[:address],
                class: "form-control",
                placeholder: "Find a car by address",
                style: "border-right: none; margin-left:1px; width: 20vw;"
              %>
              <%= submit_tag "Search", class: "btn btn-success", style: "border-radius: 0 25px 25px 0; border-left:none; position: relative; right: 1px;" %>
              <% end %>
     </div>
</nav>

app/views/shared/_top-header.html.erb
<header style="background: black; height: 500px;" class="d-flex align-items-center">
  <%# <form class="example" action="action_page.php">
    <input type="text" placeholder="Search your car.." name="search" style="width: 300px">
    <button type="submit"></button>
  </form> %>


  <h1>This is the home page</h1>
    <div>
      <h2 style="color:white;">Are you ready for Adventure?</h2>
      <h3 style="color:white;">Let's begin...</h3>
      <div class="d-flex mt-4">
        <%= link_to "Sign up", new_user_registration_path, class:"btn btn-light me-3", style:"width:100px"  %>
        <%= link_to "Login", new_user_session_path, class:"btn btn-outline-light", style:"width:100px"   %>
      </div>
    </div>
  </header>

app/views/shared/fake.html.erb
<%# defalut %>
<div class="d-flex justify-content-center" style="border-radius: 15px; width 100%; height:450px">
  <div>
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="width: 600px; border-radius: 15px 0px 0px 15px"/>
  </div>
  <div class = "ms-2">
    <div>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="width: 300px;"/>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="width: 300px; border-radius: 0px 15px 0px 0px"/>
    </div>
    <div>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="width: 300px"/>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" style="width: 300px; border-radius: 0px 0px 15px 0px"/>
    </div>
  </div>
</div>

<%# five input pictures ver %>

<div class="d-flex justify-content-center" style="border-radius: 15px; width 100%; height:450px">
  <% photos = @car.photos %>
  <div>
    <%= cl_image_tag photos[0].key, style:"width: 600px; border-radius: 15px 0px 0px 15px" %>
  </div>
  <div class = "ms-2">
    <div>
      <%= cl_image_tag photos[1].key, style:"width: 300px;" %>
      <%= cl_image_tag photos[2].key, style:"width: 300px; border-radius: 0px 15px 0px 0px" %>
    </div>
    <div>
      <%= cl_image_tag photos[3].key, style:"width: 300px;" %>
      <%= cl_image_tag photos[4].key, style:"width: 300px; border-radius: 0px 15px 0px 0px" %>
    </div>
  </div>
</div>


<div class="container marketing mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5" style="width: 700px; border: solid 2px  #e6e6e6">
    <h2>Log in</h2>

    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Log in", class:"btn btn-success" %>
    </div>

    <% end %>
    <hr>

    <%= link_to "Sign up", new_user_registration_path, class:"mb-3 btn btn-outline-success"  %>
    </div>
  </div>
</div>