config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/show'
  root to: "pages#home"

  resources :users do
    resources :reviews
  end

  resources :cars do
    resources :rentals, only: [:new, :create]
  end

  get "my_bookings", to: "rentals#booked_cars", as: "my_bookings"
  get "my_bookings/:id", to: "rentals#show_booked_car", as: "show_booked_rental"
  get "my_bookings/:id/receive", to: "rentals#rental_receive", as: "receive_rental"
  get "my_bookings/:id/return", to: "rentals#rental_return", as: "return_rental"
  get "my_rented_cars/:id/deliver", to: "rentals#owner_rental_deliver", as: "owner_deliver_rental"
  get "my_rented_cars/:id/receive", to: "rentals#owner_rental_receive", as: "owner_receive_rental"
  get "my_rented_cars", to: "rentals#my_rented_cars", as: "my_rented_cars"
  get "my_rented_cars/:id", to: "rentals#show_owner_rental", as: "show_owner_rental"
  patch "rental/:id/owner_acceptance", to: "rentals#update_owner_acceptance", as: "accept_rental"

  resources :rentals do

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date
  # has_one :review

  def self.returned_cars?(user)
    resp = false
    user.rentals.each do |rental|
      if rental.returned
        resp = true
        break
      end
    end
    return resp
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def booked_cars
    @booked_cars = current_user.rentals
  end

  def my_rented_cars
    @rented_cars = owner_rented_cars
  end

  def show_booked_car
    @rental = Rental.find(params[:id])
    @markers = [{
      lat: @rental.car.latitude,
      lng: @rental.car.longitude
    }]
    @price = (@rental.end_date - @rental.start_date).to_i * @rental.car.price.to_i
    @days = (@rental.end_date - @rental.start_date).to_i
  end

  def show_owner_rental
    @rental = Rental.find(params[:id])
    @markers = [{
      lat: @rental.car.latitude,
      lng: @rental.car.longitude
    }]
    @price = (@rental.end_date - @rental.start_date).to_i * @rental.car.price.to_i
    @days = (@rental.end_date - @rental.start_date).to_i
  end

  def new
    @rental = Rental.new
    @car = Car.find(params[:car_id])
  end

  def create
    @rental = Rental.new(new_car_params)
    @car = Car.find(params[:car_id])
    @rental.car = @car
    @rental.user = current_user
    @rental.total_cost = ((@rental.end_date - @rental.start_date).to_i * @rental.car.price.to_i)
    if @rental.save
      redirect_to show_booked_rental_path(@rental)
    else
      render "cars/show", status: :unprocessable_entity
    end
  end

  def rental_receive
    @rental = Rental.find(params[:id])
  end

  def rental_return
    @rental = Rental.find(params[:id])
  end

  def owner_rental_deliver
    @rental = Rental.find(params[:id])
  end

  def owner_rental_receive
    @rental = Rental.find(params[:id])
  end

  def update
    @rental = Rental.find(params[:id])
    if @rental.update(new_car_params)
      if current_user == @rental.car.owner
        redirect_to show_owner_rental_path(@rental)
      else
        redirect_to show_booked_rental_path(@rental)
      end
    else
      render :show_owner_rental, status: :unprocessable_entity
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
  end

  def update_owner_acceptance
    @rental = Rental.find(params[:id])
    if @rental.update(owner_approval_params)
    redirect_to show_owner_rental_path(@rental)
    end
  end

  private

  def owner_rented_cars
    owner_rented_cars = []
    all_rentals = Rental.all
    all_rentals.each do |rental|
      owner_rented_cars << rental if rental.car.owner == current_user
    end
    return owner_rented_cars
  end

  def new_car_params
    params.require(:rental).permit(:owner_acceptance, :start_milage, :end_milage, :user_started_condition,
                                   :owner_started_condition, :user_end_condition, :owner_end_condition, :start_date,
                                   :end_date)
  end

  def owner_approval_params
    params.require(:rental).permit(:owner_acceptance)
  end
end

app/views/rentals/my_rented_cars.html.erb
<header>
  <div class="p-5 text-center bg-light">
    <h1 class="header-heading">Hey <%= current_user.first_name%>! <span><i class="fa-solid fa-hands-clapping"></i></span></h1>

    <h4 class="mt-5">All your rented cars</h4>
  </div>
</header>
<div class="container d-flex flex-wrap m-5 justify-content-left">
<% if !@rented_cars.empty? %>
<% @rented_cars.each do |rental|%>
<a style="text-decoration:none; color: black;" href="/my_rented_cars/<%=rental.id %>">
<div class="card m-3" style="width: 18rem;">
  <% photos = rental.car.photos %>
  <%= cl_image_tag photos[0].key, width: 290, height: 180, crop: :fill, class:"card-img-top"%>
  <div class="card-body">
    <h4>Your <%= rental.car.brand %> <%= rental.car.model %> rental</h4>
    <p class="card-text"><i class="fa-solid fa-calendar-days"></i> <%= rental.start_date %> to <%= rental.end_date %></p>
    <p class="card-text"><i class="fa-solid fa-location-dot"></i> Mexico City</p>
    <p class="card-text"><i class="fa-solid fa-user"></i> <%= rental.car.owner.first_name %> <%= rental.car.owner.last_name %></p>
    <p class="card-text">
    <% if rental.picked %>
    <span class="badge bg-success badge-pill badge-success">Picked</span>
    <% else %>
    <span class="badge bg-danger badge-pill badge-secondary">Non-picked</span>
    <% end %>
    </p>
  </div>
</div>
</a>
<% end %>
<% else %>
<div class="container d-flex justify-content-center">
<img class="no_content-image"src="https://res.cloudinary.com/djamfh5f6/image/upload/v1669755459/1491381-fococlipping-standard_tphv07.png" alt="Popeye thinking">
<div class="align-self-center m-5 d-flex flex-column">
<h3 class="mb-4" style="text-align:center">You don't a rental yet! </h3>
<div class="d-flex flex-row">
<%= link_to "See my posted cars", cars_path, class: "btn btn-dark btn-lg btn-block m-3" %>
<%= link_to "Post a new car", new_car_path, class: "btn btn-dark btn-lg btn-block m-3" %>
</div>
</div>
</div>
<% end %>
</div>
<div class="container text-center">
<% if !@rented_cars.empty? && Rental.returned_cars?(current_user)%>
<h2>Here is your rentals history</h2>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Car</th>
      <th scope="col">Rented to</th>
      <th scope="col">Driver review</th>
    </tr>
  </thead>
  <tbody>
<% @rented_cars.each do |rental| %>
<% if rental.returned %>
    <tr>
      <td><%= rental.car.brand %> <%= rental.car.model %></td>
      <td><%= rental.car.owner.first_name %> <%= rental.car.owner.last_name %></td>
      <td>You drive bad!</td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>
<% end %>
</div>

app/views/rentals/new.html.erb
<h1>Rent a new car</h1>
<h3>You will rent the car <%= @car.model %></h3>
<%= simple_form_for([@car, @rental]) do |f| %>
  <%= f.input :start_date, as: :date, html5: true%>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/rentals/owner_rental_deliver.html.erb
<div class="container d-flex align-items-center flex-column" style="margin-top:50px;">
  <div class="p-5" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 70vw; border-radius: 15px;">
    <h1><i class="fa-solid fa-handshake"></i> <strong>Delivery car process</strong></h1>
    <br>
    <h4>Please follow the following checklist to deliver the car to <%= @rental.user.first_name %> <%= @rental.user.last_name %> </h4>
    <%= simple_form_for(@rental) do |f| %>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Turn on the Air Conditioning or Heat and ensure it works.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Check the Gas Gauge.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Pop the Trunk
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Test the Entertainment and Navigation Systems
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <br>
      <h4>Follow the following diagram to inspect the car</h4>
      <br>
      <div class="d-flex justify-content-center mb-3">
        <img src="https://cartransportservices.com.au/wp-content/uploads/2019/08/inspection-report.jpg">
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" required>
        <label class="form-check-label" for="flexCheckDisabled">
          Inspect the Exterior
        </label>
      </div>
      <br>
      <h4>Review the rental data</h4>
      <p><strong>Car host:</strong> <%= @rental.user.first_name%> <%= @rental.user.last_name %> </p>
      <p><strong>Location:</strong> <%= @rental.car.address%></p>
      <p><strong>Rented Car:</strong> <%= @rental.car.brand%>, <%= @rental.car.model%></p>
      <%= f.input :start_milage, required: true, label: "Start car mileage" %>
      <p style="font-size:12px; margin-top:-15px">*Will be validated by the car host <%= @rental.user.first_name%> <%= @rental.user.last_name %> </p>
      <hr>
      <%= f.input :owner_started_condition, label: "I, #{@rental.car.owner.first_name} #{@rental.car.owner.last_name}, accept the conditions and ensured the car condition.", required: true %>
      <%= f.submit "Deliver car", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/rentals/owner_rental_receive.html.erb
<div class="container d-flex align-items-center flex-column" style="margin-top:50px;">
  <div class="p-5" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 70vw; border-radius: 15px;">
    <h1><i class="fa-solid fa-handshake"></i> <strong>Receive car process</strong></h1>
    <br>
    <h4>Please follow the following checklist to receive the from <%= @rental.user.first_name %> <%= @rental.user.last_name %> </h4>
    <%= simple_form_for(@rental) do |f| %>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Turn on the Air Conditioning or Heat and ensure it works.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Check the Gas Gauge.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Pop the Trunk
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Test the Entertainment and Navigation Systems
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <br>
      <h4>Follow the following diagram to inspect the car</h4>
      <br>
      <div class="d-flex justify-content-center mb-3">
        <img src="https://cartransportservices.com.au/wp-content/uploads/2019/08/inspection-report.jpg">
      </div>
      <h4><strong>End mileage: <%= @rental.end_milage %> miles</strong></h4>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" required>
        <label class="form-check-label" for="flexCheckDisabled">
          Ensure the milage fits the car's milage counter
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" required>
        <label class="form-check-label" for="flexCheckDisabled">
          Inspect the Exterior
        </label>
      </div>
      <hr>
      <%= f.input :owner_end_condition, label: "I, #{@rental.car.owner.first_name} #{@rental.car.owner.last_name}, accept the conditions and ensured the car condition and the mileage.", required: true %>
      <%= f.submit "Receive car", class: "btn btn-dark" %>
    <% end %>

  </div>
</div>

app/views/rentals/rental_receive.html.erb
<div class="container d-flex align-items-center flex-column" style="margin-top:50px;">
  <div class="p-5" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 70vw; border-radius: 15px;">
    <h1><i class="fa-solid fa-handshake"></i> <strong>Receive car process</strong></h1>
    <br>
    <h4>Please follow the following checklist to receive the car of <%= @rental.car.owner.first_name %> <%= @rental.car.owner.last_name %> </h4>
    <%= simple_form_for(@rental) do |f| %>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Turn on the Air Conditioning or Heat and ensure it works.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Check the Gas Gauge.
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Pop the Trunk
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Test the Entertainment and Navigation Systems
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled">
        <label class="form-check-label" for="flexCheckDisabled">
          Start the Car and ensure everything is in good condition.
        </label>
      </div>
      <br>
      <h4>Follow the following diagram to inspect the car</h4>
      <br>
      <div class="d-flex justify-content-center mb-3">
        <img src="https://cartransportservices.com.au/wp-content/uploads/2019/08/inspection-report.jpg">
      </div>
      <h4><strong>Start mileage: <%= @rental.start_milage %> miles</strong></h4>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" required>
        <label class="form-check-label" for="flexCheckDisabled">
          Ensure the milage fits the car's milage counter
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDisabled" required>
        <label class="form-check-label" for="flexCheckDisabled">
          Inspect the Exterior
        </label>
      </div>
      <br>
      <h4>Review the rental data</h4>
      <p><strong>Car rented from:</strong> <%= @rental.car.owner.first_name%> <%= @rental.car.owner.last_name %> </p>
      <p><strong>Location:</strong> <%= @rental.car.address%></p>
      <p><strong>Rented Car:</strong> <%= @rental.car.brand%>, <%= @rental.car.model%></p>

      <hr>
      <%= f.input :user_started_condition, label: "I, #{@rental.user.first_name} #{@rental.user.last_name}, accept the conditions and ensured the car condition and the mileage.", required: true %>
      <%= f.submit "Receive car", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/rentals/rental_return.html.erb
<div class="container d-flex align-items-center flex-column" style="margin-top:50px;">
  <div class="p-5" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 70vw; border-radius: 15px;">
    <h1><i class="fa-solid fa-handshake"></i> <strong>Return car process</strong></h1>
    <br>
    <h4>Please follow the following checklist to return the car to <%= @rental.car.owner.first_name %> <%= @rental.car.owner.last_name %> </h4>
    <%= simple_form_for(@rental) do |f| %>
      <%= f.input :end_milage, required: true, label: "End car mileage" %>
      <p style="font-size:12px; margin-top:-15px">*Will be validated by the car owner <%= @rental.car.owner.first_name%> <%= @rental.car.owner.last_name %> </p>
      <hr>
      <%= f.input :user_end_condition, label: "I, #{@rental.user.first_name} #{@rental.user.last_name}, accept the conditions, ensured the car condition is as I picked it up, and that the final mileage matches the one in the car.", required: true %>
      <%= f.submit "Return car", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/rentals/show_booked_car.html.erb
<div class="map" style="width: 100%; height: 400px; border-radius-button: 10px"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div class="main-content">
  <div class="left-content">
    <div class="border card p-3">
      <h1 class="mt-3">Your <strong><%= @rental.car.brand %>, <%= @rental.car.model %></strong> car information</h1>
      <br>
      <% photos = @rental.car.photos %>
      <%= cl_image_tag photos[0].key, width: 550, height: 300, crop: :fill, style:"border-radius: 15px 0px 0px 15px", class:"img-car", class:"img-car" %>
      <div class="d-flex flex-row justify-content-evenly">
      <div class="d-flex flex-column w-50">
      <div class="d-flex flex-row  align-items-center">
        <h3>Rental Status</h3>
        <% if !@rental.owner_acceptance %>
        <span style="margin:0 auto"class="badge bg-danger badge-pill badge-success w-25">Unapproved</span>
        <% else %>
        <span style="margin:0 auto"class="badge bg-success badge-pill badge-success w-25">Approved</span>
        <% end %>
      </div>
        <% if !@rental.owner_acceptance %>
        <p>The owner of this car has not accept this rental. This procces takes in average 1 hour.</p>
        <% else %>
        <p>Your rental is approved!</p>
        <% if @rental.start_date <= Date.new %>
        <a href="" class="btn btn-dark">Start pick up proccess</a>
        <% elsif !@rental.user_started_condition %>
        <a href="" class="btn btn-dark disabled">Start pick-up proccess on <%= @rental.start_date %></a>
        <% elsif @rental.user_started_condition && @rental.end_date >= Date.new  %>
        <%= link_to "Start the return proccess on #{@rental.end_date}", return_rental_path(@rental), class: "btn btn-dark disabled"  %>
        <% end %>
        <% end %>
      </div>
       <div class="d-flex flex-row justify-content-between">
        <div class="d-flex flex-column p-2 w-50">
        <p><span><i class="fa-solid fa-car mt-3"></i></span> <%= @rental.car.brand %>, <%= @rental.car.model %></p>
        <p><span><i class="fa-solid fa-door-open"></i> </span><%= @rental.car.number_of_doors %></p>
        </div>
        <div class="d-flex flex-column p-3">
        <p><span><i class="fa-solid fa-bolt"></i> </span><%= @rental.car.engine_size %></p>
        <p><span><i class="fa-solid fa-couch"></i> </span><%= @rental.car.engine_size %></p>
        </div>
      </div>
       </div>
    </div>
  </div>
  <div class="right-content">
    <div class="border card p-3">
    <h3>Rental details</h3>
    <div class="d-flex flex-column">
      <% if @rental.car.owner.avatar.attached? %>
      <%= cl_image_tag @rental.car.owner.avatar.key, height: 200, width: 200, class:"p-3 img-circle" %>
      <% else %>
      <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png", height: 200, width: 200, class:"p-3 img-circle"%>
      <% end %>
      <h5 style="text-align:center;"><strong><%= @rental.car.owner.first_name %> <%= @rental.car.owner.last_name %></strong></h5>
      <p  class="card-text" ><span><i class="fa-solid fa-location-dot"></i> </span><%= @rental.car.address %></p>
      <p class="card-text"><i class="fa-solid fa-calendar-days"></i> <%= @rental.start_date %> to <%= @rental.end_date %></p>
      <p class="card-text"><i class="fa-solid fa-tag"></i> <%= @rental.car.price %>€ per day</p>
      <h5>Your financial choice</h5>
      <p class="card-text"><strong>Coverage:</strong> <%= @rental.coverage %>€ for <strong><%= @days %> day(s)</strong> = <%= (@rental.coverage * @days.to_i) %>€</p>
      <p class="card-text"><strong>Excess:</strong> <%= @rental.excess %>€</p>
      <p class="card-text" style="font-size:17px">Total for <strong><%= @days %> day(s): </strong><%=@price%>€ + <%= (@rental.coverage * @days.to_i) %>€ :</p>
      <span style="font-size:18px"class="badge bg-dark badge-pill badge-success "> <%=@price + @rental.coverage * @days.to_i %>€</span>
    </div>
    </div>
  </div>

app/views/rentals/show_owner_rental.html.erb
<div class="map" style="width: 100%; height: 400px; border-radius-button: 10px"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div class="main-content">
  <div class="left-content">
    <div class="border card p-3">
      <h1 class="mt-3">Your <strong><%= @rental.car.brand %>, <%= @rental.car.model %></strong> rental car information</h1>
      <br>
      <% photos = @rental.car.photos %>
      <%= cl_image_tag photos[0].key, width: 550, height: 300, crop: :fill, style:"border-radius: 15px 0px 0px 15px", class:"img-car" %>
      <div class="d-flex flex-column">
      <div class="d-flex flex-column">
      <div class="d-flex flex-row align-items-center justify-content-between">
        <h2>Rental details</h2>
        <% if !@rental.owner_acceptance %>
        <span class="badge bg-danger badge-pill badge-success w-25">Not approved yet by you</span>
        <% else %>
        <span class="badge bg-success badge-pill badge-success w-25">Approved by you</span>
        <% end %>
      </div>
      </div>
       <div>
       <% if !@rental.owner_acceptance %>
        <h4>Rental request person </h4>
      <% else %>
        <h4>Host</h4>
       <% end %>
        <div class="d-flex flex-column p-3">
          <div>
            <p class="card-text"><span>
              <% if @rental.user.avatar.attached? %>
                <%= cl_image_tag @rental.user.avatar.key, height:40, width: 40, class:" img-circle" %></span> <%= @rental.user.first_name %> <%= @rental.user.last_name %></p>
              <% else %>
               <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png", height: 40, width: 40, class:"p-3 img-circle"%>
              <% end %>
            <p class="card-text"><span><i class="fa-solid fa-calendar-days"></i></span> <strong><%= @rental.start_date %></strong> to <strong><%= @rental.end_date %></strong> <p style="font-size:12px; margin-top:-15px">* Your <%= @rental.car.brand %>, <%= @rental.car.model %> <strong>has not other requests</strong> within this time interval.</p></p>
            <p class="card-text"><span><i class="fa-solid fa-location-dot"></i></span> <%= @rental.car.address %></p>
          </div>
        <div>
          </div>
        </div>
        <h4>Finance information </h4>
          <div class="d-flex flex-column p-3">
            <div>
              <p class="card-text"><span><i class="fa-solid fa-money-bill"></i></span> <%= @rental.car.price %>€ per day <p style="font-size:12px; margin-top:-15px">*This price was set by you when posting your car. You <strong>will not</strong> be able to change this price if you accept this rental request until <%= @rental.end_date %> when the car is returned.</p></p>
              <p class="card-text"><span><i class="fa-solid fa-sun"></i></span> <%= @days %> days<p style="font-size:12px; margin-top:-15px">*Each day corresponds to <strong>24hrs</strong>; It starts to count at the moment you deliver the car.</p></p>
              <p class="card-text"><span><i class="fa-solid fa-dollar-sign"></i></span> <%= @rental.total_cost %>€ Total<p style="font-size:12px; margin-top:-15px">*<%= @rental.user.first_name %> <%= @rental.user.last_name %> decided to book the car with a financial setting in which the total amount
              that will be blocked on its credit card is <%= @rental.excess %>€ from your approval until <strong><%= @rental.end_date %></strong> when the car is returned.</p></p>
              <p></p>
              <% if !@rental.owner_acceptance %>
                <%= link_to "Accept rental request", accept_rental_path(@rental, rental:{ owner_acceptance: true} ), data: {turbo_method: :patch}, class: "btn btn-dark"  %>
              <% end %>
            </div>
          </div>
       </div>
       </div>
    </div>
  </div>
  <div class="right-content">
    <div class="border card p-3">
    <h3><strong>Rental track</strong></h3>
    <div>
      <% if @rental.user_started_condition && @rental.owner_started_condition && !@rental.user_end_condition && !@rental.owner_end_condition%>
        <p>Rental Status: <span class="badge bg-success badge-pill badge-success">Delivered to Host</span></p>
        <%= link_to "Start car return proccess on #{@rental.end_date}", owner_receive_rental_path(@rental), class: "btn btn-dark disabled"  %>
      <% elsif !@rental.user_started_condition && !@rental.owner_started_condition && !@rental.user_end_condition && !@rental.owner_end_condition  %>
        <p>Rental Status: <span class="badge bg-danger badge-pill badge-success">Not delivered to host</span></p>
        <p>Delivery agreement: <span class="badge bg-danger badge-pill badge-success">Not accepted</span></p>
        <% if @rental.start_date <= Date.new %>
        <%= link_to "Start delivery proccess", owner_deliver_rental_path(@rental), class: "btn btn-dark"  %>
        <% else %>
        <%= link_to "Start delivery proccess on #{@rental.start_date}", owner_deliver_rental_path(@rental), class: "btn btn-dark disabled"  %>
        <% end %>
      <% elsif !@rental.user_started_condition && @rental.owner_started_condition && !@rental.user_end_condition && !@rental.owner_end_condition %>
        <p>Rental Status: <span class="badge bg-success badge-pill badge-success">Approved by you but not by the host</span></p>
      <% end %>
    </div>
    </div>
    </div>
  </div>