config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/show'
  root to: "pages#home"

  resources :users do
    resources :reviews
  end

  resources :cars do
    resources :rentals, only: [:new, :create]
  end

  get "my_bookings", to: "rentals#booked_cars", as: "my_bookings"
  get "my_bookings/:id", to: "rentals#show_booked_car", as: "show_booked_rental"
  get "my_bookings/:id/receive", to: "rentals#rental_receive", as: "receive_rental"
  get "my_bookings/:id/return", to: "rentals#rental_return", as: "return_rental"
  get "my_rented_cars/:id/deliver", to: "rentals#owner_rental_deliver", as: "owner_deliver_rental"
  get "my_rented_cars/:id/receive", to: "rentals#owner_rental_receive", as: "owner_receive_rental"
  get "my_rented_cars", to: "rentals#my_rented_cars", as: "my_rented_cars"
  get "my_rented_cars/:id", to: "rentals#show_owner_rental", as: "show_owner_rental"
  patch "rental/:id/owner_acceptance", to: "rentals#update_owner_acceptance", as: "accept_rental"

  resources :rentals do

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner, class_name: :User, foreign_key: :user_id
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos

  def self.brands
    getting_models
  end

  def unavailable_dates
    rentals.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  private

  def self.getting_models
    all.map do |car|
      car.model
    end
  end
  
  include PgSearch::Model
  pg_search_scope :search_by_car,
                  against: [ :brand, :model, :number_of_seats, :category, :color],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      unless params[:address].empty?
        selection = Car.near(params[:address], 20)
        @cars = selection.search_by_car(params[:query])
      else
        @cars = Car.search_by_car(params[:query])
      end
    else
      @cars = Car.all
    end
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "car_info_window", locals: { car: car})
      }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_user
    if @car.save
      redirect_to @car
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @rental = Rental.new
    @car = Car.find(params[:id])
    @markers = [{
      lat: @car.latitude,
      lng: @car.longitude
    }]
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :edit, :unprocessable_entity
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path, status: :see_other
  end

  private

  def car_params
    params.require(:car).permit(:category, :brand, :model, :year, :color, :number_of_doors, :number_of_seats,
                                :engine_size, :price, :address, photos: [])
  end
end

app/views/cars/_car_info_window.html.erb
<h2><%=car.owner.first_name%>'s <%=car.brand%> <%=car.model%></h2>
<p>Year of manufacture <%=car.year%></p>
<p>Color: <%=car.color%></p>
<p>Number of seats: <%=car.number_of_seats%></p>
<p>Number of doors: <%=car.number_of_doors%></p>
<p>Engine Size (L): <%=car.engine_size%></p>
<p>Address:  <%=car.address%></p>

app/views/cars/edit.html.erb
<h1>Edit car</h1>

<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <%= simple_form_for(@car) do |f| %>
        <%= f.input :category %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :engine_size , as: :numeric%>
        <%= f.input :year , as: :integer%>
        <%= f.input :color %>
        <%= f.input :number_of_seats, as: :numeric %>
        <%= f.input :number_of_doors, as: :numeric %>
        <%= f.input :price, as: :float%>
        <%= f.input :address, as: :string%>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="d-flex justify-content-end me-5" style="width-100vw; ">
  <h1 style="margin-right:5vw; margin-top:1vh">Cars available to you</h1>
</div>
<div class="d-flex ">
<div class="m-3" style="width: 100%; height: 100vh; position: sticky; top:0; border-radius: 15px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div>
<%@cars.each_with_index do |car|%>
  <div class="d-flex ">
      <div class="card-trip m-3" style="border-radius: 15px; width: 500px">
        <% photos = car.photos %>
        <%= cl_image_tag photos[0].key, width: 500, height: 300, crop: :fill, style:"border-radius: 15px 0px 0px 15px" %>
        <div class="card-trip-infos">
          <div class="d-flex justify-content-between" style="width: 100%">
            <div>
              <h2><%= car.owner.first_name%>'s <%= car.brand%> <%=car.model%></h2>
              <p>Year of manufacture <%=car.year%></p>
              <p>Color: <%=car.color%></p>
              <p>Number of seats: <%=car.number_of_seats%></p>
              <p>Number of doors: <%=car.number_of_doors%></p>
              <p>Engine Size (L): <%=car.engine_size%></p>
            </div>
            <div>
              <h2 class="card-trip-pricing mt-3">£<%=car.price.round%></h2>
              <%= link_to "See Offer", car_path(car), class: "mt-3 btn btn-dark"%>
              <%= cl_image_tag car.owner.avatar.key, height: 45, width: 45, class: "card-trip-user avatar-bordered"%>
            </div>
          </div>
        </div>
      </div>
  </div>
<% end %>
</div>

</div>

app/views/cars/new.html.erb
<div class="container marketing card border p-1">
<h1>Create a car</h1>
  <div class="row d-flex justify-content-center">
    <div class="col-10 p-4">
      <%= simple_form_for(@car) do |f| %>
        <%= f.input :category %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :engine_size , as: :numeric%>
        <%= f.input :year , as: :integer%>
        <%= f.input :color %>
        <%= f.input :number_of_seats, as: :numeric %>
        <%= f.input :number_of_doors, as: :numeric %>
        <%= f.input :price, as: :float%>
        <%= f.input :address, as: :string%>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-dark"%>
      <% end %>
     </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class = "d-flex m-4 align-items-center" style="width: 700px">
<% if @car.owner.avatar.attached? %>
<%= cl_image_tag @car.owner.avatar.key, height: 85, width: 85, class:"ms-5 me-3" ,style: "padding: 1px; border-radius: 50px; box-shadow: 0 0 10px rgba(0,0,0,0.2); border: white 2px solid; ;"%>
<% else %>

<% end %>
  <h1><%=@car.owner.first_name%>'s <%=@car.brand%> <%=@car.model%></h1>
</div>

<div class="d-flex justify-content-center" style="border-radius: 15px; width 100%; height:450px">
  <% photos = @car.photos %>
  <div style='width: 600px; height: 400px; border-radius: 15px 0px 0px 15px;' >
    <%= cl_image_tag photos[0].key, width: 600, height: 400, crop: :fill, style:"border-radius: 15px 0px 0px 15px" %>
  </div>
  <div class = "ms-2">
    <div>
      <%= cl_image_tag photos[1].key, width: 300, height: 200, crop: :fill %>
      <%= cl_image_tag photos[2].key, width: 300, height: 200, crop: :fill, style:"width: 300px; border-radius: 0px 15px 0px 0px" %>
    </div>
    <div>
      <%= cl_image_tag photos[3].key, width: 300, height: 200, style:"width: 300px;", crop: :fill %>
      <%= cl_image_tag photos[4].key, width: 300, height: 200, style:"width: 300px; border-radius: 0px 0px 15px 0px" ,crop: :fill %>
    </div>
  </div>
</div>


<div class="d-flex justify-content-center">
  <div class="d-flex justify-content-evenly" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 70vw; border-radius: 15px;">
    <div class="mt-5 ms-5" style="bottom: 0; right: 0">
      <h2>Rental info</h2>
      <p><i class="fa-solid fa-car mt-3"></i><span> </span><%=@car.brand%> <%=@car.model%></p>
      <p><i class="fa-solid fa-business-time"></i><span> </span>Year of manufacture <%=@car.year%></p>
      <p><i class="fa-solid fa-droplet"></i><span> </span>Color: <%=@car.color%></p>
      <p><i class="fa-solid fa-chair"></i></i><span> </span>Number of seats: <%=@car.number_of_seats%></p>
      <p><i class="fa-solid fa-door-open"></i><span> </span>Number of doors: <%=@car.number_of_doors%></p>
      <p><i class="fa-solid fa-bolt"></i><span> </span>Engine Size (L): <%=@car.engine_size%></p>
      <h4><i class="fa-solid fa-tags"></i></i><span> </span>£<%=@car.price.round%></h4>
      <% if current_user && current_user != @car.owner %>
      <div class="d-flex justify-content-center">
        <a href="#new_rental" class="btn btn-dark mt-3 me-2">Rent it!</a>
      </div>
      <% elsif current_user && current_user == @car.owner %>
        <div class="d-flex">
          <div class="m-1">
            <%= link_to "Edit this car!", edit_car_path(@car), class: "btn btn-dark"%>
          </div>
          <div class="m-1">
            <%= button_to "Delete", car_path(@car), data:{confirm: "Are you sure?"}, method: :delete, class: "btn btn-dark"%>
          </div>
        </div>
      <% else %>
        <div class="d-flex justify-content-center">
          <%= link_to "Sign up to rent!", new_user_registration_path, class: "btn btn-dark mt-3 me-2"%>
        </div>
      <% end %>
    </div>
    <div>
      <div style="width: 40vw; height: 500px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-4">
  <hr style="width: 75%">
</div>

<% if current_user && current_user != @car.owner %>
  <div class="container" data-controller="coverage-form">
    <h2 style="text-align:center;"><strong>Rent this car!</strong></h2>
    <div class="m-4 d-flex flex-row justify-content-between">
        <div id="new_rental" class="card p-4" style="border-radius:10px; width: 40vw;">
          <h4>Select the days you will like to rent this car</h4>
          <%= simple_form_for([@car, @rental], data: { coverage_form_target: "form" }) do |f| %>
          <%= f.input :excess, as: :hidden, value: 1000, input_html: { data: { coverage_form_target: "excessValue" }} %>
          <%= f.input :start_date, as: :date, html5:true %>
          <%= f.input :end_date, html5:true %>
          <%= f.submit 'Request rental', class:"btn btn-dark",  data: { action: "click->coverage-form#alert" }  %>
        </div>
        <div id="new_rental" class="card p-4" style="border-radius:10px; width: 40vw;" data-coverage-form-target="finance">
          <h4 class="mb-4">Select your coverage and excess level</h4>
          <div class="d-flex flex-row">
            <p style="text-align:center; font-size: 23px; margin: 0 auto; font-weight: 400; color: white" class="badge bg-dark badge-pill badge-success mt-1 mb-1">$<span data-coverage-form-target="coverageContainer">25</span>£ Coverage</p>
            <p style="text-align:center; font-size: 23px; margin: 0 auto; font-weight: 400; color: white " class="badge bg-dark badge-pill badge-success mt-1 mb-1">$<span data-coverage-form-target="excessContainer">1000</span>£ Excess</p>
          </div>
          <div class="excess-input">
          <%= f.input :coverage, as: :range, input_html: {min:"0", max:"50",data:{action: "change->coverage-form#update", coverage_form_target: "coverage"}}, class:"form-range", label:false%>
          </div>
          <p class="mt-2">Increase the coverage to decrease the excess charged to your credit card. <strong>The coverage should be payed daily.</strong></p>
          <div data-coverage-form-target="message" class="d-none">
          </div>
        </div>
          <%end%>
    </div>
    </div>
  </div>
  </div>
<%end%>